[package]
name = "fastladder-bookwalker"
version = "0.1.2"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]

[dependencies]
clap = "2.23"
hyper = "0.10"
hyper-rustls = "0.6"
select = "0.4"
serde = "1.0"
serde_json = "1.0"
url = "1.4"
