[package]
name = "fastladder-bookwalker"
version = "0.1.1"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]

[dependencies]
clap = "2.23"
hyper = "0.10"
hyper-native-tls = "0.2"
select = "0.4"
serde = "0.9"
serde_json = "0.9"
url = "1.4"
